Update Multi

diff --git a/Multi b/Multi
--- a/Multi
+++ b/Multi
@@ -6,37 +6,22 @@
 
 ## Script to keep-alive your DNSTT server domain record query from target resolver/local dns server
 
-## Run this script excluded to your VPN tunnel  (split vpn tunneling mode)
+## Run this script excluded from your VPN tunnel (split VPN tunneling mode)
 
-## run command: ./globe-james.sh l
+## run command: ./globe-fast1.sh l
 
-
-
-## Your DNSTT Nameserver & your Domain `A` Record
-
-NS='ns.sg1-udp.tunnel.cx'
-NS1='dns.james.lamok.cf'
-NS2='dns.xs-1.optnl.com'
-NS3='sg2ray-dns.mainssh.com'
-NS4='dns.sg7c62.fcafessh.net'
-NS5='ns-sg4dns.srvdns.us' 
-NS6='ns.wstest.abalos-zoey.online' 
-A='dns.ssh-sg-3.vpnsvr.net'
-
-## Repeat dig cmd loop time (seconds) (positive interger only)
+## Repeat dig command loop time (seconds) (positive integer only)
 
 LOOP_DELAY=5
 
+## Define the aligned nameservers and hosts
 
-
-## Add your DNS here
-
-declare -a HOSTS=('124.6.181.20' '124.6.181.12')
-
-
+declare -A SERVERS=(
+    ["ph2.vpnjantit.com"]="121.54.70.132"
+    ["dns.ids-3.optnl.com"]="124.6.181.20 124.6.181.36 124.6.181.12"
+)
 
 ## Linux' dig command executable filepath
-
 ## Select value: "CUSTOM|C" or "DEFAULT|D"
 
 DIG_EXEC="DEFAULT"
@@ -45,100 +30,69 @@ DIG_EXEC="DEFAULT"
 
 CUSTOM_DIG=/data/data/com.termux/files/home/go/bin/fastdig
 
-
-
 ######################################
-
 ######################################
-
 ######################################
-
 ######################################
-
 ######################################
 
 VER=0.1
 
 case "${DIG_EXEC}" in
-
- DEFAULT|D)
-
- _DIG="$(command -v dig)"
-
- ;;
-
- CUSTOM|C)
-
- _DIG="${CUSTOM_DIG}"
-
- ;;
-
+DEFAULT|D)
+    _DIG="$(command -v dig)"
+    ;;
+CUSTOM|C)
+    _DIG="${CUSTOM_DIG}"
+    ;;
 esac
 
 if [ ! $(command -v ${_DIG}) ]; then
-
- printf "%b" "Dig command failed to run, " \
-
- "please install dig(dnsutils) or check " \
-
- "\$DIG_EXEC & \$CUSTOM_DIG variable inside $( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )/$(basename "$0") file.\n" && exit 1
-
+    printf "Dig command failed to run, please install dig (dnsutils) or check DIG_EXEC & CUSTOM_DIG variables inside $( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )/$(basename "$0") file.\n"
+    exit 1
 fi
 
 endscript() {
-
- unset NS NS1 NS2 NS3 NS4 NS5 NS6 NS7 NS8 NS9 NS10 NS11 NS12 NS13 NS14 NS15 NS16 NS17 NS18 NS19 NS20 NS21 NS22 NS23 NS24 A LOOP_DELAY HOSTS _DIG DIG_EXEC CUSTOM_DIG T R M
-
- exit 1
-
+    unset LOOP_DELAY SERVERS _DIG DIG_EXEC T R M
+    exit 1
 }
 
 trap endscript 2 15
 
-check(){
-for ((i=0; i<"${#HOSTS[*]}"; i++)); do
-  for R in "${NS}" "${A}" "${NS1}" "${A1}" "${NS2}" "${A2}" "${NS3}" "${A3}"; do
-   T="${HOSTS[$i]}"
-     $(timeout -k .3 .3 ${_DIG} @${T} ${R})  && M=31 || M=32;
-   echo -e "\e[1;${M}m\$ R:${R} D:${T}\e[0m"
-   unset T R M
-  done
- done
+check() {
+    for server in "${!SERVERS[@]}"; do
+        for host in ${SERVERS["$server"]}; do
+            T="${host}"
+            R="${server}"
+            
+            # Add ping and host lookup
+            ping -c 1 "${T}" &  # Ping the nameserver in the background
+            host "${R}" &  # Host lookup in the background
+            
+            timeout -k 3 3 ${_DIG} @${T} "${R}"  # Remove the domain name
+            if [ $? -eq 0 ]; then
+                M=32
+            else
+                M=31
+            fi
+            echo -e "\e[${M}m:${R} D:${T}\e[0m"
+        done
+    done
 }
 
-
 echo "DNSTT Keep-Alive script <Discord @civ3>"
-
-echo -e "DNS List: [\e[1;34m${HOSTS[*]}\e[0m]"
-
+echo "DNS List:"
+for server in "${!SERVERS[@]}"; do
+    echo -e "\e[34m${server}\e[0m -> ${SERVERS["$server"]}"
+done
 echo "CTRL + C to close script"
 
- "${LOOP_DELAY}" -eq 1  && let "LOOP_DELAY++";
+if [ "${LOOP_DELAY}" -eq 1 ]; then
+    let "LOOP_DELAY++"
+fi
 
-case "${@}" in
-
- loop|l)
-
- echo "Script loop: ${LOOP_DELAY} seconds"
-
- while true; do
-
-  check
-
-  echo '.--. .-.. . .- ... .     .-- .- .. -'
-
-  sleep ${LOOP_DELAY}
-
- done
-
- ;;
-
- *)
-
- check
-
- ;;
-
-esac
-
-exit 0
+while true; do
+    check
+    echo '.--. .-.. . .- ... .     .-- .- .. -'
+    sleep ${LOOP_DELAY}
+done
